apiVersion: v1
kind: Service
metadata:
  name: tenant-log-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: tenant-log-api