apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-api
  labels:
    role: master-api
spec:
  replicas: 3
  selector:
    matchLabels:
      role: master-api
      tier: web
  template:
    metadata:
      labels:
        role: master-api
        tier: web
    spec:
      containers:
      - name: master-api
        image: osmeltechcm/master-api
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: SERVER
          value: "db.k9erp.net"
        - name: DATABASE
          value: "multitenant-db-k9erp"
        - name: USER
          value: "k9erp_service"
        - name: PASSWORD
          value: "DN~4/Skc>=DXAMUZ"